services:
  - type: web
    name: tm-fetch
    env: node
    plan: starter
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/.cache/ms-playwright"
